services:
  db:
    image: postgres:15
    container_name: postgres15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DB}
    env_file:
      - .env  #relative to docker-compose.yml,regardless of what you set as the build.context
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${SQL_PORT}:5432"

volumes:
  pg_data: